CREATE TABLESPACE "TS_STAT_FX" 
EXTENT MANAGEMENT LOCAL  
AUTOALLOCATE  
SEGMENT SPACE MANAGEMENT AUTO  
DATAFILE '/data/Oracle/oradata/orcl/TS_STAT_FX.dbf' 
SIZE 50M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;

DROP USER STAT_FX CASCADE;

CREATE USER STAT_FX IDENTIFIED BY Passw0rd DEFAULT TABLESPACE TS_STAT_FX TEMPORARY TABLESPACE TEMP;

GRANT RESOURCE TO STAT_FX;
GRANT CONNECT TO STAT_FX;
GRANT CREATE SESSION TO STAT_FX;
GRANT CREATE VIEW TO STAT_FX;
GRANT EXECUTE ON DBMS_LOCK TO STAT_FX;
grant unlimited tablespace to STAT_FX;


--new version 生产环境

CREATE TABLESPACE "TS_EPM_STAGE_EGG01" 
EXTENT MANAGEMENT LOCAL  
AUTOALLOCATE  
SEGMENT SPACE MANAGEMENT AUTO  
DATAFILE '/u01/app/oracle/oradata/DSDB/TS_EPM_STAGE_EGG01.dbf' 
SIZE 50M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;

DROP USER EPM_STAGE_EGG01 CASCADE;

CREATE USER EPM_STAGE_EGG01 IDENTIFIED BY Passw0rd DEFAULT TABLESPACE TS_EPM_STAGE_EGG01 TEMPORARY TABLESPACE TEMP;

GRANT RESOURCE TO EPM_STAGE_EGG01;
GRANT CONNECT TO EPM_STAGE_EGG01;
GRANT CREATE SESSION TO EPM_STAGE_EGG01;
GRANT CREATE VIEW TO EPM_STAGE_EGG01;
GRANT EXECUTE ON DBMS_LOCK TO EPM_STAGE_EGG01;
grant unlimited tablespace to EPM_STAGE_EGG01;


--new version 开发环境
CREATE TABLESPACE "TS_EPM_PLN_APP52" 
EXTENT MANAGEMENT LOCAL  
AUTOALLOCATE  
SEGMENT SPACE MANAGEMENT AUTO  
DATAFILE '/u01/app/oracle/oradata/cpzf/TS_EPM_PLN_APP52.dbf' 
SIZE 50M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;

DROP USER EPM_PLN_APP52 CASCADE;

CREATE USER EPM_PLN_APP52 IDENTIFIED BY Passw0rd DEFAULT TABLESPACE TS_EPM_PLN_APP52 TEMPORARY TABLESPACE TEMP;

GRANT RESOURCE TO EPM_PLN_APP52;
GRANT CONNECT TO EPM_PLN_APP52;
GRANT CREATE SESSION TO EPM_PLN_APP52;
GRANT CREATE VIEW TO EPM_PLN_APP52;
GRANT EXECUTE ON DBMS_LOCK TO EPM_PLN_APP52;
grant unlimited tablespace to EPM_PLN_APP52;


drop user ABC cascade;
drop tablespace ABC including contents and datafiles cascade constraint;
