CREATE TABLESPACE "TS_STAT_FX" 
EXTENT MANAGEMENT LOCAL  
AUTOALLOCATE  
SEGMENT SPACE MANAGEMENT AUTO  
DATAFILE '/data/Oracle/oradata/orcl/TS_STAT_FX.dbf' 
SIZE 50M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;

DROP USER STAT_FX CASCADE;

CREATE USER STAT_FX IDENTIFIED BY Passw0rd DEFAULT TABLESPACE TS_STAT_FX TEMPORARY TABLESPACE TEMP;

GRANT RESOURCE TO STAT_FX;
GRANT CONNECT TO STAT_FX;
GRANT CREATE SESSION TO STAT_FX;
GRANT CREATE VIEW TO STAT_FX;
GRANT EXECUTE ON DBMS_LOCK TO STAT_FX;
grant unlimited tablespace to STAT_FX;